module.exports = {
  type: process.env.TYPEORM_DB_CONNECTION,
  host: process.env.TYPEORM_DB_HOST,
  username: process.env.TYPEORM_DB_USERNAME,
  password: process.env.TYPEORM_DB_PASSWORD,
  port: process.env.TYPEORM_DB_PORT,
  sid: process.env.TYPEORM_DB_SID,
  database: process.env.TYPEORM_DB_NAME,
  connectString: `(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(Host = ${process.env.TYPEORM_DB_HOST})(Port =${process.env.TYPEORM_DB_PORT})))(CONNECT_DATA =(sid ='dbvm')(SERVER=dedicated)))`,
  synchronize: false,
  logging: false,
  entities: ['build/entity/**/*.js'],
  migrations: ['build/migration/**/*.js'],
  subscribers: ['build/subscriber/**/*.js'],
  cli: {
    entitiesDir: ['build/entity'],
    migrationsDir: ['build/migration'],
    subscribersDir: ['build/subscriber'],
  },
  extra: {
    homogeneous: true,
    poolAlias: 'default',
    poolIncrement: 1,
    poolMax: 10,
    poolMin: 0,
    poolPingInterval: 60,
    poolSize: 10,
    poolTimeout: 60,
  },
}
