export const DB_INSERT_ERROR = 'DbInsertError'
export const DB_UPDATE_ERROR = 'DbUpdateError'
export const ENTITY_NOT_FOUND_ERROR = 'EntityNotFound'
export const DATA_NOT_FOUND_ERROR = 'DataNotFound'
export const INVALID_CREDENTIALS_ERROR = 'InvalidCredentials'
export const PAYLOAD_VALIDATION_ERROR = 'PayloadValidationError'
export const UNEXPECTED_ERROR = 'UnexpectedError'
